### PR TITLE
Events slider

### LINKED ISSUE #269: Slider for the cards
### Description

I want to add a slider for cards instead of all of them showing up all at a time. This will make website more attractive.

Please assign this issue to me under GSSoC'23.

### Screenshots

Screenshot (76)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by I-shika**
Example: Closes #269 

## Changes proposed

Addition of a slider for events cards.

## Note to reviewers

I have changed only index.jsx for events other changes are done for pull reauest for latest merge.

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Resolve merge conflicts

**Comment by Susmita-Dey** [comment]
image

**Also this doesn't look good. There's no space between the cards**

**Comment by I-shika** [comment]
I have done the required changes @Susmita-Dey . Please review it

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Thanks for contributing:)

**Pull request merged**
