### PR TITLE
fix: responsive faq section

### PR DESCRIPTION
**Pull request by AbhiPatel10**
## Screenshots

image

### CODE REVIEW

**Comment by abdulmoizsheraz** [comment]
Hi! I want to work on this issue Assign me!

**Comment by AbhiPatel10** [comment]
> Hi! I want to work on this issue Assign me!

It's a Pull Request, I have already finished this issue that's why i make a PR. so if you want to work then find other issue in our website and make an issue.

**Comment by abdulmoizsheraz** [comment]
> > Hi! I want to work on this issue Assign me!
> 
> It's a Pull Request, I have already finished this issue that's why i make a PR. so if you want to work then find other issue in our website and make an issue.

Sorry I did not see that i have open issuse check plz

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
