### PR TITLE
Closes #202 - Go To Top Button Covers Link in Footer

### LINKED ISSUE #202: Add Auto Comment Feature to Improve Collaboration
**Issue Description:**
As an active contributor to your open-source project, I believe that implementing an auto-comment feature would greatly enhance collaboration and communication within the project. This feature would automatically generate comments in response to specific events, such as when an issue is opened, a pull request is created, an issue is assigned, or an issue is unassigned.

**Feature Details:**
- When an issue is opened, the auto-comment should greet the author and provide a brief acknowledgement and request for additional context.
- When a pull request is opened, the auto-comment should greet the author, express gratitude, and remind them to follow the project's contributing guidelines.
- When an issue is closed, the auto-comment should thank the author for their contribution and encourage further engagement.
- When an issue is assigned to someone, the auto-comment should notify the assignee and encourage them to start working on it.
- When an issue is unassigned from someone, the auto-comment should notify the assignee about the change and suggest reassignment if they are offline.

**Benefits:**
- Improved communication and engagement with contributors.
- Provides clear instructions and acknowledgements for various events.
- Enhances collaboration by setting expectations and providing reminders.
- Reduces manual effort by automating comment generation.

**Acceptance Criteria:**
- The auto-comment feature should be implemented using the "wow-actions/auto-comment" GitHub Action.
- Comments should be appropriately customized for each event, mentioning relevant parties and providing the necessary information.
- The auto-comment workflow should trigger on the following events: issues opened, pull requests opened, issues closed, issues assigned, and issues unassigned.
- The feature should be added to the project's existing GitHub Actions workflow file.

**Additional Context:**
Feel free to ask any questions or seek clarification regarding the auto-comment feature. I'm excited about contributing to your project and believe this enhancement will greatly benefit its community.

### PR DESCRIPTION
**Pull request by ManasMadan**
## Changes proposed
The Go To Top Button Positioning has been changed to solve the issue

## Screenshots
image

### CODE REVIEW

**Comment by ManasMadan** [comment]
@prnvtripathi Merging this PR closes issue #201

**Comment by AbhiPatel10** [comment]
Looks good just make that button little bit small

**Comment by ManasMadan** [comment]
@AbhiPatel10, Please check now this is how it looks
image

**Comment by AbhiPatel10** [comment]
Looks good thank you for your contributions.

**Review by AbhiPatel10 — APPROVED** [review]

**Pull request merged**
