### PR TITLE
update: Change team data

### LINKED ISSUE #222: [Enhancement] Adding actual team data to the team page
### Description

Right now the team page consists of filler text, I'll work on to change it in actual data.

### Screenshots

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by prnvtripathi**
## Fixes Issue
resolves #222 
## Changes proposed

Added actual team data instead of filler contents

### CODE REVIEW

**Comment by prnvtripathi** [comment]
@devs-in-tech/devsintech-web-team can someone review this PR

**Review by Susmita-Dey — COMMENTED** [review]
image

No image? 👀

**Comment by prnvtripathi** [comment]
> image
> 
> No image? 👀

i wasn't able to find his github

**Comment by Susmita-Dey** [comment]
its_abhirup

**Pull request closed without merging**
