### PR TITLE
footer visibility resolve

### LINKED ISSUE #379: [OTHER]: Footer visibility
### What would you like to share or ask?

Footer links not visible properly due to its color and also footer content appearance not looks good as it display flex,

I would like to make it perfect under the GSSoC tag please assign me this task.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by BhartiNagpure**
#379 Footer visibility issue

Closes#379

## Changes proposed
I'm changing the color of text to visible the text also change the social icon color change flex direction of footer and added heart to copyright.

## Screenshots

Screenshot 2023-07-13 134407

## Note to reviewers

@prnvtripathi please review PR .

### CODE REVIEW

**Comment by BhartiNagpure** [comment]
@prnvtripathi I am done with my work please review it.

**Review by prnvtripathi — COMMENTED** [review]
Can you position the social media icons to center aligned below the list, make the logo a little bit smaller and the name "DevsInTech" one size larger

**Comment by BhartiNagpure** [comment]
> Can you position the social media icons to center aligned below the list, make the logo a little bit smaller and the name "DevsInTech" one size larger

@prnvtripathi sure

**Comment by BhartiNagpure** [comment]
@prnvtripathi resolve changes please review it.

**Review by prnvtripathi — APPROVED** [review]
LGTM

**Comment by BhartiNagpure** [comment]
@prnvtripathi please review it.

**Pull request merged**
