### PR TITLE
[UPDATED] Added Transition to Hero Section

### PR DESCRIPTION
**Pull request by Mahitej28**
- Added Fade In transition to the `Hero Section` main text that is `Devs In Tech Community`
- Updated `package.json` file, added husky scripts so that people working on the project don't face pre-commit hook issue

This PR is created in reference to Issue No.: #85

### CODE REVIEW

**Comment by AbhiPatel10** [comment]
> * Added Fade In transition to the `Hero Section` main text that is `Devs In Tech Community`
> * Updated `package.json` file, added husky scripts so that people working on the project don't face pre-commit hook issue
> 
> This PR is created in reference to Issue No.: #85

Precommit is not an issue it helps to make a strict project so that everyone can work similarly.

**Comment by AbhiPatel10** [comment]
In issue 85 you were working on smooth scrolling but you make a pr for Transition in hero section ? why ?

**Comment by Mahitej28** [comment]
@AbhiPatel10 As I reviewed the recent website,  the smooth scroll feature is already added by somone and so I decided to enhance it by adding transition to the scrolling

**Comment by AbhiPatel10** [comment]
Only animation to header is looks weird.

**Comment by Mahitej28** [comment]
Should I put it to the entire hero section?

**Comment by Mahitej28** [comment]
> @AbhiPatel10 As I reviewed the recent website, the smooth scroll feature is already added by somone, although the part was assigned to me and so I decided to enhance it by adding transition to the scrolling

Can you please explain how someone else got the same issue assigned which was identified to me, and if that was the case why wasn't I informed earlier about the same?

**Comment by AbhiPatel10** [comment]
> > @AbhiPatel10 As I reviewed the recent website, the smooth scroll feature is already added by somone, although the part was assigned to me and so I decided to enhance it by adding transition to the scrolling
> 
> Can you please explain how someone else got the same issue assigned which was identified to me, and if that was the case why wasn't I informed earlier about the same?

I don't know whole team handling this repo so sometime may be some conflict are there.

for now we are not thinking to add animation on website so you can find other issue and start working on it.

**Pull request closed without merging**
