### PR TITLE
feat: lazyLoading is added

### PR DESCRIPTION
**Pull request by shraddha761**
#279

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
Hey @shraddha761 Can you share a video recording of what's changed/added?

I can't see any changes in the deployed version of your PR

**Comment by Killer2OP** [comment]
@Susmita-Dey you'll see this between website loading time form previous to after lazy loading added

**Comment by shraddha761** [comment]
@Susmita-Dey you'll see the difference will website load before lazy loading added and after

**Comment by Susmita-Dey** [comment]
Hey @devs-in-tech/devsintech-web-team Can you review this PR once?

**Comment by shraddha761** [comment]
@Susmita-Dey please merge this pr

**Comment by prnvtripathi** [comment]
@Susmita-Dey , there is some error in preview deployment of this PR, I'm not able to see the changes

**Pull request closed without merging**
