### PR TITLE
Fixed : issue #192

### PR DESCRIPTION
**Pull request by parthpathakpp1**
## Changes proposed

Previously the cards were going on top of the Navbar while hovering . Now it is fixed . 

## Screenshots
**Before**

https://github.com/devs-in-tech/DevsInTech/assets/85991449/6aabda9e-2ffc-42c0-9e57-818bd1a84c34

**After**

https://github.com/devs-in-tech/DevsInTech/assets/85991449/ceb6e67d-be48-40b8-a4ed-1e553816b06e

### CODE REVIEW

**Review by prnvtripathi — APPROVED** [review]
Looks good to merge.

**Comment by prnvtripathi** [comment]
Thank you for contributing.

**Comment by parthpathakpp1** [comment]
> Thank you for contributing.

Can you please give me label .

**Comment by prnvtripathi** [comment]
> Can you please give me label . 
Sure. 😊

**Comment by parthpathakpp1** [comment]
@prnvtripathi I think you will have to change the "GSSoC23" label to 'gssoc23' otherwise it will not be counted. So could you please change it ??

**Pull request merged**
