### PR TITLE
feat: make navbar translucent

### PR DESCRIPTION
**Pull request by karthiknadar1204**
## Changes proposed

Made the navbar translucent to make it look more attractive

## Screenshots

https://www.awesomescreenshot.com/video/18938102?key=65cb7172996388e313eca2fc45162549

### CODE REVIEW

**Review by prnvtripathi — CHANGES_REQUESTED** [review]
Remove all the unnecessary comments from the code.

**Comment by karthiknadar1204** [comment]
In a bit

**Comment by karthiknadar1204** [comment]
Done @prnvtripathi

**Review by prnvtripathi — APPROVED** [review]
LGTM   :)

**Comment by karthiknadar1204** [comment]
@prnvtripathi @Susmita-Dey Please add the appropriate labels

**Pull request merged**
