### PR TITLE
Created GitHub Action for Code Formatting ⚡

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Fixes Issue

#287 

## Changes proposed

I have created a new workflow which Check format of code means Pretier and workflow code is added into  : `.github/workflows`

### CODE REVIEW

**Comment by Nishitbaria** [comment]
> ## Fixes Issue
> #287
> 
> ## Changes proposed
> I have created a new workflow which Check format of code means Pretier and workflow code is added into : `.github/workflows`

Hey @Susmita-Dey To run this workflow you have to give some Permissions

**Comment by Susmita-Dey** [comment]
@Nishitbaria What kind of permissions?

**Comment by Nishitbaria** [comment]
> @Nishitbaria What kind of permissions?

image

**Comment by Nishitbaria** [comment]
> > @Nishitbaria What kind of permissions?
> 
> image


@Susmita-Dey, this permission is granted through the Repository settings.

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
