### PR TITLE
 Added Newsletter Subscription to DevsInTech Website

### PR DESCRIPTION
**Pull request by Nishitbaria**
Description:
This pull request adds a newsletter subscription feature to the DevsInTech website. Users can now sign up for the newsletter to stay updated with the latest articles and announcements. The newsletter subscription is linked with the Hashnode newsletter service.
## Changes proposed

- Added a newsletter subscription form to the website.
- Created a new API endpoint `/api/subscribes` for handling newsletter subscriptions.
- Integrated the Axios library to make a POST request to the Hashnode API for subscribing users to the newsletter.
- Added validation for the email field in the subscription form.
- Displayed a success message when the subscription is successful.
- Styled the form and success message using Tailwind CSS.

## Screenshots

**Video**
[video](https://github.com/Nishitdev/Vite-ReactApp/assets/123718275/44cb4aa9-1ed6-4211-ad70-18c330dae982)
## Note to reviewers

Please review and merge this pull request to enable newsletter subscriptions on the DevsInTech website.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@Susmita-Dey ,please merge my pull request

**Review by Susmita-Dey — COMMENTED** [review]
What's the use of new.html file?

**Comment by Nishitbaria** [comment]
Hey @Susmita-Dey  I have deleted the unused file , please review

**Review by Susmita-Dey — APPROVED** [review]
Kindly remove the value of publicationId. I have noted it and will add on Vercel. 

Instead use the following:
```
const publicationId = process.env.NEXT_PUBLIC_PUBLICATION_ID
```

I'll add the value to the Vercel env variable.

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Make the changes ASAP

**Comment by Nishitbaria** [comment]
@Susmita-Dey ,I have updated environment variable

**Review by Susmita-Dey — APPROVED** [review]
Great job!!

**Comment by Nishitbaria** [comment]
@Susmita-Dey ,Can i create an issue for adding voice and chat assistant to devsintech website which answers FAQ questions,helps in navigation through voice and many more.

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey ,Can i create an issue for adding voice and chat assistant to devsintech website which answers FAQ questions,helps in navigation through voice and many more.

Sure

**Pull request merged**
