### PR TITLE
feat: implement contributors page

### PR DESCRIPTION
**Pull request by karthiknadar1204**
## Fixes Issue #250 

please refer pr #332

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
Hey @karthiknadar1204 Please install axios properly. Even if I merge your PR, it won't get deployed. Also, beside this share the screen recording by using OBS or Awesome Screen Recorder Extension.

**Comment by karthiknadar1204** [comment]
Could you please share the command to install axios, I have been using the same command "pnpm add axios -w"

As for the recording, it is the same i shared in the previous pr.

I just installed the awesome recorder you speak of, will use it for forthcoming pr's.

As for axios, Could you help me with the installation, I have installed it and it runs on my local system as well, 
Screenshot 2023-07-04 at 1 54 53 PM


In the above screenshot as well, the axios package was installed perfectly on my system and gave me the desired results.
Could I coordinate with members of the web-dev team we spoke of earlier to fix this.
It's almost done, just a package issue, should be done swiftly.

**Comment by Susmita-Dey** [comment]
Use: `pnpm add axios`

**Comment by karthiknadar1204** [comment]
it was giving error, will try it right away again

**Comment by karthiknadar1204** [comment]
Screenshot 2023-07-04 at 3 43 07 PM

Same error

**Comment by Susmita-Dey** [comment]
Check it out:- https://github.com/pnpm/pnpm/issues/4225#issuecomment-1046799049

**Comment by karthiknadar1204** [comment]
Running this command:
pnpm add axios --workspace-root

**Comment by karthiknadar1204** [comment]
How do i push these changes,like do i push the package.json files

**Comment by karthiknadar1204** [comment]
Screenshot 2023-07-04 at 4 04 35 PM

The command ran successfully with changes in these 2 files

**Comment by Susmita-Dey** [comment]
Just push the changes

**Comment by karthiknadar1204** [comment]
okie in a min

**Comment by karthiknadar1204** [comment]
Done @Susmita-Dey

**Review by Susmita-Dey — APPROVED** [review]
Great job! Thanks for contributing:)

**Comment by karthiknadar1204** [comment]
Thank you so much

**Comment by karthiknadar1204** [comment]
I forgot to make it responsive with tailwind CSS, raising an issue for the same

**Pull request merged**
