### PR TITLE
Added Interactive AI Voice and Text Chat Assistant

### PR DESCRIPTION
**Pull request by Nishitbaria**
This pull request adds an interactive voice and text assistant to the Devsin Tech website, enhancing user experience by providing seamless navigation and answering frequently asked questions (FAQs).

## Features Added

1. **Voice Assistant Integration**: Users can now interact with the website using voice commands, making it more accessible and hands-free.

2. **Text Assistant Integration**: In addition to voice, the text assistant allows users to communicate through text inputs, providing flexibility in how users interact with the website.

3. **FAQ Answering**: The assistant is trained on a comprehensive set of frequently asked questions (FAQs) related to Devsin Tech, enabling it to provide quick and accurate responses to user queries.

4. **Navigation Support**: Users can ask the assistant to guide them through various sections and pages of the website, providing an intuitive and user-friendly experience.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@Susmita-Dey  @prnvtripathi ,please review and merge my pull request

**Comment by Nishitbaria** [comment]
@prnvtripathi ,please review and merge my pull request

**Review by prnvtripathi — APPROVED** [review]
LGTM

**Comment by Nishitbaria** [comment]
@prnvtripathi ,please assign appropriate label and level  to this pull request

**Comment by Nishitbaria** [comment]
@prnvtripathi ,please assign the appropriate gssoc label and level to this pull request

**Pull request merged**
