### PR TITLE
Fix carousel box sizes, added auto carousel, and changed button layout

### PR DESCRIPTION
**Pull request by abhipatel0211**
## Changes proposed
- Fixing the problem of inconsistent box sizes within the carousel, improving the overall appearance and usability.
- Converting the carousel into an auto carousel for automatic transitions between slides, providing a more engaging user experience.
- Adjusting the button layout, moving them from the side to the bottom of the carousel for better user accessibility and intuition.

## Screenshots
- before changes
Screenshot (5)
-After changes
Screenshot (7)

## Note to reviewers

In this pull request, I have made several improvements to the carousel feature:

Fixed the issue of inconsistent box sizes within the carousel: Previously, the varying sizes of the boxes caused a poor user experience. Now, the boxes display consistently, enhancing the overall appearance and usability of the carousel.

Converted the carousel to an auto carousel: With this update, the carousel will automatically transition between slides, providing a more engaging and seamless user experience. Users will no longer need to manually interact with the carousel.

Adjusted the button layout: The buttons, which were initially located on the side of the carousel, have been moved to the bottom. This change is aimed at improving user accessibility and intuition, making it easier for users to navigate the carousel.

I kindly request the reviewers to focus on the code changes related to these enhancements. Your feedback and suggestions are greatly appreciated, especially if you notice any potential issues or areas that require further refinement.

Thank you for your time and assistance in reviewing this pull request.

## Label Request

Dear reviewers, I kindly request the addition of the "gssoc" , "enhancements" label to this pull request. As I am participating in the GirlScript Summer of Code, this label will help in identifying my contributions. Thank you for your attention and assistance.

### CODE REVIEW

**Review by prnvtripathi — COMMENTED** [review]
There's some issue with responsiveness can you look into that. The margin on left side isn't ideal

**Comment by abhipatel0211** [comment]
yes i made some changes as per requirements but there is an other issue with the nav bar with the social media icons due to it there is an issue of center as it is taking the whole space 

- with symbol 
Screenshot (13)

- without symbol 
Screenshot (12)

**Comment by abhipatel0211** [comment]
@prnvtripathi @Susmita-Dey  can you please review the pull request and add the tags of gssoc

**Comment by Susmita-Dey** [comment]
@abhipatel0211 Issue no?

I see that you're not following the CONTRIBUTING GUIDELINES as you haven't linked any issue no here which was being assigned to you.

**Comment by abhipatel0211** [comment]
Sorry i haven't raised the issue

**Comment by abhipatel0211** [comment]
Should I raise now?

**Comment by Susmita-Dey** [comment]
GSSoC endeed I guess @abhipatel0211

**Comment by abhipatel0211** [comment]
Ok no issue but can you merge it or I have to raise the issue first and then you will merge

**Comment by abhipatel0211** [comment]
i have raised the issue #452  can you please assign that issue to me and review this PR @Susmita-Dey

**Comment by abhipatel0211** [comment]
@Susmita-Dey  @prnvtripathi  can you please review this PR

**Comment by AbhiPatel10** [comment]
@abhipatel0211 Do not change UI just make Automation of Carousal that will be good.

**Comment by abhipatel0211** [comment]
@AbhiPatel10 @Susmita-Dey @prnvtripathi  can you please review the changes

**Review by prnvtripathi — APPROVED** [review]
LGTM

**Pull request merged**
