### PR TITLE
Redesign stats section

### LINKED ISSUE #300: [Feature] Redesign the numbers section in About section
### Description

Currently the numbers/statistics section in the about section does not look good. It looks more as a static component.
I would like to redesign the component to somewhat like shown below.

Responsive cards would be added along with animations and hover effects which would improve the UI and UX of the page.

### Screenshots

Currently:
image

Proposed:
image

### Additional Information

Please assign me the issue under GSSoC23.

### PR DESCRIPTION
**Pull request by abhinav-m22**
* Closes #300 

## Changes proposed

Redesigned the stats section. Designed the cards with some on-hover animations and the counter to provide a visually appealing component.

## Screenshots

image

### CODE REVIEW

**Comment by prnvtripathi** [comment]
Hey, this looks great, can you do a couple of things, reduce the hover translation to `"hover:translate-y-2"` and add a gradient to the background.

**Comment by abhinav-m22** [comment]
Okay I'll do the required 👍

**Comment by abhinav-m22** [comment]
@prnvtripathi 
Please check now


image

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Add some margin at the top and bottom of the cards to provide some spacing between the above text and below video

**Comment by abhinav-m22** [comment]
@Susmita-Dey Please check now

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
