### PR TITLE
fix: Resolved Errors in feature-request.yml File and styles.yml File

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Changes proposed
- **Resolved Errors in feature-request.yml and styles.yml File.**

## Note to reviewers

- **I hope after these changes made working Correctly Now.**

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @Susmita-Dey . Please Review on this PR and Add Valid Level Label and GSSOC'23 Label. Thank You !

**Comment by Susmita-Dey** [comment]
Hey @NarendraKoya999 GSSoC has already ended on 10th August

**Comment by NarendraKoya999** [comment]
@Susmita-Dey . No Problem. Please Merged with Valid Labels under GSSOC'23. I know these Points are not Counted. Thank You !

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
