### PR TITLE
feat: migrated to `pnpm` #37

### LINKED ISSUE #37: [Feature] migrate to `pnpm`
### Description

currently, we are using `npm` int his project but we can use `pnpm`.

Why pnpm?
- it's faster
- lightweight
- disk efficient
- etc

### Screenshots

_No response_

### Additional Information

I want to work on this issue

### PR DESCRIPTION
**Pull request by priyankarpal**
## Changes
- migrated to pnpm 
- improved the README.md file
## How to run it locally?
- install dependencies using `pnpm i`
- run in using `pnpm dev`
- upgrade dependencies using `pnpm upgrade --latest`

## Demo

https://user-images.githubusercontent.com/88102392/236608138-19ea58cf-b022-4517-89b7-b58e45a7ccbc.mp4

### CODE REVIEW

**Review by himanshu1221 — APPROVED** [review]
Great Work @priyankarpal :100: 
LGTM :+1:

**Comment by AbhiPatel10** [comment]
I'm also able to use NPM, we need to restrict that and stick into pnpm only.

add `"npm": "Please-use-pnpm"` into engines inside package.json


image

**Comment by priyankarpal** [comment]
> I'm also able to use NPM, we need to restrict that and stick into pnpm only.
> 
> add `"npm": "Please-use-pnpm"` into engines inside package.json
> 
> image

I have added `"preinstall": "npx only-allow pnpm"` already. Don't worry I changed the docs also

**Comment by AbhiPatel10** [comment]
Yes, you are right, but if I use NPM, it gives an error, but after installing node_modules and the package-lock file, that must not be installed. We need to add NPM and yarn to both in engines. that gives an error before installing anything.

image

**Comment by priyankarpal** [comment]
> Yes, you are right, but if I use NPM, it gives an error, but after installing node_modules and the package-lock file, that must not be installed. We need to add NPM and yarn to both in engines. that gives an error before installing anything.
> 
> image

ok

**Review by AbhiPatel10 — APPROVED** [review]

**Comment by AbhiPatel10** [comment]
Done! Thank you for your contribution @priyankarpal

**Pull request merged**
