### PR TITLE
Added dockerfile - Dockerized the App

### PR DESCRIPTION
**Pull request by abhinav2712**
## Changes proposed

Added a Dockerfile in the root directory. Here are the steps through which anyone can run their application on docker:

1. Open a terminal, navigate to the project's root directory, and run the following command:

``` docker build -t devsin-tech ```

This command will build a Docker image named "devsin-tech" based on the Dockerfile.

2. Run a Docker container from the built image. Execute the following command in the terminal:

``` docker run -p 3000:3000 devsin-tech ```

This command runs a Docker container from the "devsin-tech" image, mapping port 3000 from the container to port 3000 on your local machine. This will allow you to access the application in your browser at ``` http://localhost:3000/ ```

## Screenshots

image

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
Hey @abhinav2712 I don't know why you made this PR. This issue was assigned to @abhinav-m22 and he have already done this by #268 

Kindly follow the contributing guidelines of this repository.

**Comment by abhinav2712** [comment]
> Hey @abhinav2712 I don't know why you made this PR. This issue was assigned to @abhinav-m22 and he have already done this by #268
> 
> Kindly follow the contributing guidelines of this repository.

This is why I made the PR:
image

**Comment by Susmita-Dey** [comment]
@abhinav2712 Both of you have same names so it's a mistake. You should have checked the name under assigned section of the issue

**Comment by abhinav2712** [comment]
> @abhinav2712 Both of you have same names so it's a mistake. You should have checked the name under assigned section of the issue

Ok

**Pull request closed without merging**
