### PR TITLE
style: (frontend)Added background image issue-125

### LINKED ISSUE #125: Adding background image
### What would you like to share or ask?

website looks too simple ,adding a background image can make it attractive. 
Screenshot (46)
for example,
 If want change, do assign it to me under GSSOC 2023 .  :)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ManishaSwain8**
close #125 

## Fixes Issue
Added background image only

Do check out , and inform if any changes required.   : |)

### CODE REVIEW

**Comment by himanshu1221** [comment]
@AbhiPatel10 I feel this background in good but this should cover the whole website what do you say?

**Comment by ManishaSwain8** [comment]
> @AbhiPatel10 I feel this background in good but this should cover the whole website what do you say?

In my opinion img covering whole website will look terrible. (Just suggestion: In other parts gradients  colors can be applied)

**Comment by ManishaSwain8** [comment]
I had added full background to the website in recent push , is it ok or previous one was better .
Do inform if  changes req.

**Comment by himanshu1221** [comment]
> There was no response so I thought to put on chats ...I had added full background to the website in recent push , is it ok or previous one was better .
> Do inform if  changes req. @himanshu1221 

Hey @ManishaSwain8 as i am a bit occupied with my exams so wont be able to Review it 
@AbhiPatel10 will do it shortly or else I'll try to do it by the end of the weekend

**Comment by ManishaSwain8** [comment]
> > There was no response so I thought to put on chats ...I had added full background to the website in recent push , is it ok or previous one was better .
> > Do inform if  changes req. @himanshu1221
> 
> Hey @ManishaSwain8 as i am a bit occupied with my exams so wont be able to Review it @AbhiPatel10 will do it shortly or else I'll try to do it by the end of the weekend

ohh that's not a problem at all , I was just making sure.
Best of luck : |)

**Comment by AbhiPatel10** [comment]
We do not need to add any background image as it will slow down the website and it's not as per our website design

**Pull request closed without merging**
