### PR TITLE
#98 underline resolved

### LINKED ISSUE #98: [style]: Add underline on hover on the buttons of navbar
### What's the style idea?

We need to improve : The present hover effect on the navbar items seems to be incomplete. Please assign this task to me so that i can add a left to right underline effect on the items.
Screenshot 2023-05-21 at 12 23 12 PM

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by piyushkhurana2019**
Closes #98

## Changes proposed

I have added Animated underline effect on the items of navbar with the same gradient as you asked

## Screenshots

https://github.com/devs-in-tech/DevsInTech/assets/96003210/e0fbcea4-93db-44ad-aa19-5fdcfc5d1def

### CODE REVIEW

**Review by himanshu1221 — CHANGES_REQUESTED** [review]
Hey @piyushkhurana2019 it works like a charm!
It would be great if you implement it using Tailwind CSS

**Comment by piyushkhurana2019** [comment]
> 

okay sir working on that

**Comment by piyushkhurana2019** [comment]
> Hey @piyushkhurana2019 it works like a charm! It would be great if you implement it using Tailwind CSS

@himanshu1221 , Sir as there are many stylings under after: section so its difficult to write in one line tailwind css,
can i add my styling after making the @layer components {
} like this :-


Screenshot 2023-05-22 at 11 52 51 PM

**Comment by AbhiPatel10** [comment]
Just add Hover effect of text color, Underline looks weird

**Comment by piyushkhurana2019** [comment]
> Just add Hover effect of text color, Underline looks weird

ok sir noted

**Comment by AbhiPatel10** [comment]
@piyushkhurana2019 are you working on this ?

**Comment by piyushkhurana2019** [comment]
> @piyushkhurana2019 are you working on this ?

sorry sir i don't know how to write properties in tailwind CSS, so not able to work on it

**Comment by AbhiPatel10** [comment]
Okay @piyushkhurana2019 No problem

**Pull request closed without merging**
