### PR TITLE
feat(frontend): improved faq section

### LINKED ISSUE #370: Improving the FAQ section
### What would you like to share or ask?

The FAQ section can be redesigned so that it looks more good and impressive
Please assign this issue so that I can redesign it and if you like then you may merge it.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Illaf**
## Fixes Issue

closes #370 
## Changes proposed

faq  section changed according to the design shown and approved

### CODE REVIEW

**Comment by Illaf** [comment]
@prnvtripathi  @Susmita-Dey Please merge this pull request

**Comment by Illaf** [comment]
@Susmita-Dey  @prnvtripathi Please merge this pull request!

**Comment by Illaf** [comment]
@prnvtripathi @Susmita-Dey Please merge this pull request.Only four days are left for gssoc!

**Comment by Susmita-Dey** [comment]
@Illaf Any screenshots do you have?

**Pull request closed without merging**
