### PR TITLE
feat: created contributors page

### PR DESCRIPTION
**Pull request by karthiknadar1204**
## Changes proposed

Have used the github API to fetch contributors data and made it into cards , have made the page fully responsive as wel

## Screenshots

https://github.com/devs-in-tech/DevsInTech/assets/95973644/0bafd5e4-192e-4f31-9c18-41a8fbc32d5e

## Note to reviewers
The page probably still has a lot of scope for improvement, if need any more changes, please do share them

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
I myself have a small styling i thought I could apply on this page, will try it and if feasible, will open an issue pertaining the same @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@karthiknadar1204 There's some error message in Netlify while building your proposed changes. Kindly fix it by installing axios package properly.

image

**Comment by karthiknadar1204** [comment]
Could you share any command  for the same, I used pnpm add axios -w

It worked perfectly on my system

**Comment by Susmita-Dey** [comment]
Hey @devs-in-tech/devsintech-web-team Can you kindly help him?

**Comment by karthiknadar1204** [comment]
Could you please help @devs-in-tech/devsintech-web-team .
Can't seem to figure it out

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Please use Tailwind classes instead of plain CSS and install axios package properly. Check Tailwind docs, you'll understand how to use it. 

Also, rename `Contributors_Api.jsx` file to `contributors.js` Best approach would be creating a file under components and then making a contributor component and after that import that component in this file under pages folder.

**Comment by karthiknadar1204** [comment]
Converted plain css to tailwind css components and changed the file name, as for axios, The package seems to be perfectly installed by the command "pnpm add axios -w"
Screenshot 2023-07-04 at 1 54 53 PM

**Comment by karthiknadar1204** [comment]
> Please use Tailwind classes instead of plain CSS and install axios package properly. Check Tailwind docs, you'll understand how to use it.
> 
> Also, rename `Contributors_Api.jsx` file to `contributors.js` Best approach would be creating a file under components and then making a contributor component and after that import that component in this file under pages folder.

I tried the approach to make it a component and then import it in page but I spent almost 2 hrs figuring out why wasn't the API call getting rendered because it was continuously showing 404 page not found so did it at once in the pages section

**Comment by karthiknadar1204** [comment]
I tried to pull the changes but it was showing multiple merge conflicts so opened a second pr #340 @Susmita-Dey

**Pull request closed without merging**
