### PR TITLE
feat(frontend): aligned font of the events page

### PR DESCRIPTION
**Pull request by Illaf**
## Changes proposed
The font in the events page was different from the rest of the website .Hence I have removed font weight in the page so that uniformity and theme is maintained in the entire website.
Screenshot (28)

### CODE REVIEW

**Review by prnvtripathi — CHANGES_REQUESTED** [review]
Remove `font-bold` from the content only and not from the headings.

**Comment by Illaf** [comment]
@prnvtripathi Ok

**Comment by Illaf** [comment]
@prnvtripathi done!

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
image

**Align this text to the left and not centered and remove font-bold from here**
Also, update your branch

**Comment by Illaf** [comment]
@Susmita-Dey okay

**Comment by Illaf** [comment]
> image
> 
> **Align this text to the left and not centered and remove font-bold from here** Also, update your branch

@Susmita-Dey Done!👍

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Comment by Susmita-Dey** [comment]
@prnvtripathi Can you kindly review this PR? 

We have to merge it

**Comment by Illaf** [comment]
@Susmita-Dey Please merge this pull request

**Comment by Susmita-Dey** [comment]
@devs-in-tech/devsintech-web-team Someone review and merge this pull request

**Review by prnvtripathi — APPROVED** [review]
Looks good to merge :)

**Review by prnvtripathi — APPROVED** [review]
Solved some merge conflicts.

**Pull request merged**
