### PR TITLE
feat: Social Media Icons on header         GsSoC'23

### PR DESCRIPTION
**Pull request by Nikhil1017**
## Changes proposed
1) Replace the join us button in the top right corner of the header with Social Media Icons that redirect to DevInTech's respective social media profiles

## Screenshots

image
image

### CODE REVIEW

**Comment by Nikhil1017** [comment]
@himanshu1221  what do you think?

**Comment by Nikhil1017** [comment]
@himanshu1221

**Comment by AbhiPatel10** [comment]
@Nikhil1017 in tablet view why icons not shown ?

**Comment by Nikhil1017** [comment]
@AbhiPatel10 Thanks for pointing out, I fixed the bug

**Comment by AbhiPatel10** [comment]
@Nikhil1017  Show menubar after 856px so it will be a responsive

**Comment by Nikhil1017** [comment]
@AbhiPatel10 I think it is already responsive, the icons show in the menu bar after the menu bar appears.

**Comment by Susmita-Dey** [comment]
Hey @Nikhil1017 Kindly update your branch and put the issue number you're working on

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

**Pull request merged**
