### PR TITLE
feat: dark mode with social media icons GsSoC'23

### LINKED ISSUE #79: [style]: Improved Social media links and Toggle button for Dark mode.
### What's the style idea?

1) Place all the Social media links in the Header right side by replacing all the buttons with Social Media Icons.
2) Add a Toggle Button between Dark Mode and Light Mode.

### Add screenshots

SImilar to this

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Nikhil1017**
## Fixes Issue 
Closes #79 

## Changes proposed
1) Add Dark Mode to the website and a Toggle button
2) Add social media icons  for Discord, twitter, Github and replace the Join Us Button in the top right corner.

## Screenshots

image
image
image
image
image
image

### CODE REVIEW

**Comment by Nikhil1017** [comment]
@himanshu1221  What do you think?

**Comment by himanshu1221** [comment]
Hey @Nikhil1017 i am bit occupied i will surely review or PR by this weekend

**Comment by Nikhil1017** [comment]
@himanshu1221 can you comment now please

**Comment by Nikhil1017** [comment]
@AbhiPatel10 that is unfortunate even though I was assigned to work on it. Anyways how about I delete the dark mode settings and Icon and instead of the dark mode icon, I replace it with linkedin link, so that you can atleast keep the social media icons.

**Pull request closed without merging**
